import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState, useEffect } from 'react';
import { BsSearch } from 'react-icons/bs';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';
import Logo from '../public/weather.png'

export default function Home() {
  const [city, setCity] = useState('Toronto');
  const [weather, setWeather] = useState({});
  const [maps, setMaps] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=0b55267d4aa279d979faa31278da2504`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      console.log(response.data);
    });
    setCity('');
    setLoading(false);
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div>
        <Head>
          <title>Weather - Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        {/* Overlay */}
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
        {/* Background image */}
        <Image
          src='https://images.unsplash.com/photo-1584267385494-9fdd9a71ad75?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80'
          alt='background with a landscape showing a beautiful place'
          layout='fill'
          className='object-fill'
        />

        {/* Search */}
        <header>
          <nav className='relative flex justify-between mb-8 items-center p-3 w-full bg-black/60 z-[5]'>
            <Image src={Logo} className='max-w-[45px] max-h-[45px] align-middle'/>
              <ul className='flex text-white itens-center mr-1'>
                <li className='mr-5' id='#'>Home</li>
                <li className='mr-5 ' id='#'><a href='https://openweathermap.org/' target='blank'>API</a></li>
              </ul>
          </nav>
        </header>
        
        
        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
          <form
            onSubmit={fetchWeather}
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'
          >
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className='bg-transparent border-none text-white focus:outline-none text-2xl'
                type='text'
                placeholder='Search city'
              />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>

        {/* Weather/Maps */}
        {weather.main && <Weather data={weather} />}
      </div>
    );
  }
}
