import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import { BsSearch } from 'react-icons/bs'

export default function Home() {

const [city, setCity] = useState('')
const [weather, setWeather] = useState({})
const [loading, setLoading] = useState(false)

const url = `https://api.openweathermap.org/data/2.5/weather?q=dubai&units=imperial&appid=0b55267d4aa279d979faa31278da2504`;

const fetchWeather = (e) =>{
  e.preventDefault();
  setLoading(true)
  axios.get(url).then((response) =>{
    setWeather(response.data)
    console.log(response.data)
  })
  setCity('')
  setLoading(false)
} 
   return (
    <div>
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]'/>
      <Image src="https://images.unsplash.com/photo-1545193544-312983719627?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" 
      layout='fill'
      alt='weather image showing differents temperatures'
      className='object-cover'
      />

    </div>
  )
}


// START AGAIN IN 20 MINUTES //